// File generated based on Firebase project: studio-3328096157-e3f79
// Generated by manual configuration from google-services.json

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM26X4EXiP3c4uqmLiF1yqXSnRlnWRePY',
    appId: '1:97120825720:web:71fa701dd5d4561f8bd88d',
    messagingSenderId: '97120825720',
    projectId: 'studio-3328096157-e3f79',
    authDomain: 'studio-3328096157-e3f79.firebaseapp.com',
    storageBucket: 'studio-3328096157-e3f79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM26X4EXiP3c4uqmLiF1yqXSnRlnWRePY',
    appId: '1:97120825720:android:35db27e28bfd838d8bd88d',
    messagingSenderId: '97120825720',
    projectId: 'studio-3328096157-e3f79',
    storageBucket: 'studio-3328096157-e3f79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM26X4EXiP3c4uqmLiF1yqXSnRlnWRePY',
    appId: '1:97120825720:ios:com_scholesa_app',
    messagingSenderId: '97120825720',
    projectId: 'studio-3328096157-e3f79',
    storageBucket: 'studio-3328096157-e3f79.firebasestorage.app',
    iosBundleId: 'com.scholesa.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM26X4EXiP3c4uqmLiF1yqXSnRlnWRePY',
    appId: '1:97120825720:macos:com_scholesa_app',
    messagingSenderId: '97120825720',
    projectId: 'studio-3328096157-e3f79',
    storageBucket: 'studio-3328096157-e3f79.firebasestorage.app',
    iosBundleId: 'com.scholesa.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM26X4EXiP3c4uqmLiF1yqXSnRlnWRePY',
    appId: '1:97120825720:windows:scholesa_app',
    messagingSenderId: '97120825720',
    projectId: 'studio-3328096157-e3f79',
    storageBucket: 'studio-3328096157-e3f79.firebasestorage.app',
  );
}
